variables:
  POSTGRES_DB: "skybook"
  POSTGRES_USER: "skybook"
  POSTGRES_PASSWORD: "skybook"
  READ_DB_URL: "postgres://skybook:skybook@postgres:5432/skybook"
  WRITE_DB_URL: "postgres://skybook:skybook@postgres:5432/skybook"
  SUPERUSER_DB_URL: "postgres://skybook:skybook@postgres:5432/skybook"
  IP_HASH_SECRET: "iphashsecret"
  COOKIE_SIGNING_SECRET: "cookiesigningsecret"
  NOTIFICATION_URL_KEY: "a3e1df35903c431ac811c3d4f1eba753950fc1ac4e758edf38309f9fa5c10086"
  NOTIFICATION_URL_IV: "eb2199b617f31dabacc06de2"

test:
  image: oven/bun:1
  services:
    - name: postgres:latest
      alias: postgres
  before_script:
    - bun install
    - cp config.sample.toml config.toml
  script:
    - until bash -c 'echo > /dev/tcp/postgres/5432' 2>/dev/null; do sleep 1; done
    - bun run src/startup/migrate.ts
    - bun test
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - when: manual
      allow_failure: true
