[server]
captcha_implementation = "cap" # cap (trycap.dev) | cloudflare
[rate_limits]
auth_window_ms = 60000             # 1 minute
auth_limit = 5
entry_creation_window_ms = 60000   # 1 minute
entry_creation_limit_anonymous = 2
entry_creation_limit_elevated = 3
alteration_window_ms = 10000       # 10 seconds
alteration_limit_elevated = 8
alteration_limit_anonymous = 3
fetch_window_ms = 20000            # 20 seconds
fetch_limit = 25

[sessions]
expiry_days = 7

[tokens]
expiry_hours = 24

[jobs]
expiration_sweep_interval_minutes = 30

[ip_blocking]
global_block_threshold = 10
proxy_addresses_blocked = false
vpn_addresses_blocked = false
tor_addresses_blocked = false

[users]
indefinite_locking_threshold = 3
