[kaiju]
version = "0.0 (TESTING)"
proxies_between = 1
environment = "development"
[server]


[captcha]
implementation = "cap"                                       # cap (trycap.dev) | cloudflare
token_property_name = "cap-token"
site_key = "89a2b7836c"
secret_key = "sk-ToUHcl2gqvIdZqM6JFi7VEct01osu8pPZwOUUUP0kY"
challenge_url = "http://localhost:9000/"
verification_url = "http://localhost:9000/siteverify"

[users]
indefinite_locking_threshold = 3

[filter]
# Enforce a default filter on all instances
# By default all filters specified here are false, 
# which allows instance owners to toggle them manually.
# If a new filter is added, it is to be added here and in src/config.ts.

derogatory = false


[fields]
author_max_length = 50
typical_max_length = 500

[rate_limits]
auth_window_ms = 60000             # 1 minute
auth_limit = 5
entry_creation_window_ms = 60000   # 1 minute
entry_creation_limit_anonymous = 2
entry_creation_limit_elevated = 3
alteration_window_ms = 10000       # 10 seconds
alteration_limit_elevated = 8
alteration_limit_anonymous = 3
fetch_window_ms = 20000            # 20 seconds
fetch_limit = 25

[sessions]
expiry_days = 7

[tokens]
expiry_hours = 24

[jobs]
expiration_sweep_interval_minutes = 30

[ip_blocking]
automated_enforcements_enabled = false
global_block_threshold = 15
proxy_addresses_blocked = true         #
vpn_addresses_blocked = true           #
tor_addresses_blocked = true           #
