[skybook]
proxies_between = 1
environment = "development"
subdomain_vanity = true
cloudflare = true
user_enforcements_enabled=true
domain="skybook.localhost"
header="Skybook is currently under development, stability can not be guaranteed."
invitation_required=true

[captcha]
implementation = "cap"                                       # cap (trycap.dev) | cloudflare
token_property_name = "cap-token" # cap-token | cf-turnstile-response
site_key = "89a2b7836c" # 89a2b7836c

challenge_url = "http://localhost:9000/"
verification_url = "http://localhost:9000" #https://challenges.cloudflare.com/turnstile/v0/siteverify

[users]
indefinite_locking_threshold = 3
expiration_threshold_days = 365
expiration_grace_period_days = 7

[posts]
perPage = 15

[fields]
author_max_length = 50
typical_max_length = 500

[rate_limits]
auth_window_ms = 60000             # 1 minute
auth_limit = 5
entry_creation_window_ms = 60000   # 1 minute
entry_creation_limit_anonymous = 2
entry_creation_limit_elevated = 3
alteration_window_ms = 10000       # 10 seconds
alteration_limit_elevated = 8
alteration_limit_anonymous = 3
fetch_window_ms = 20000            # 20 seconds
fetch_limit = 25

[sessions]
expiry_days = 7

[tokens]
expiry_hours = 24

[jobs]
# How often to check for accounts which haven't
# been seen for at least users.expiration_threshold_days
# and schedule them for deletion 
expiration_sweep_interval_minutes = 60
lift_enforcements_interval_minutes = 60

[ip_blocking]
automated_enforcements_enabled = false
global_block_threshold = 15
blocking_timeframe_days_max = 30           # As IP addresses are not permanent identifiers, we expire all IP blocks after this timeframe.
proxy_addresses_blocked = true         #
vpn_addresses_blocked = true           #
tor_addresses_blocked = true           #
