[skybook]
# If Skybook is directly accessible, you want to set this to 0.
proxies_between = 1
environment = "development"
subdomain_vanity = false
cloudflare = false

# Whether Skybook will automatically enforce actions on
# accounts which are blocked by a meaningful
# number of guestbooks
user_enforcements_enabled=false
domain="localhost"
header=""
username_max_length=20 # If altered, requires alteration of the `name` column in the `users` DB table, which defaults to VARCHAR(20)
username_min_length=3
instance_notifications=false # Notify instance owners when they receive a new entry

# Specify which notification endpoints to allow/disallow.
# Currently, Skybook supports the following endpoints:
# [ntfy, discord, matrix, custom]
instance_notification_services=["ntfy","discord","matrix","custom"] 

# Optionally specify a URL which forwards notification POST requests;
# This will replace the user-specified endpoint and put it into the request body.
# An example usage of this is a CloudFlare worker to proxy requests, hiding the origin server IP.
# If behind CloudFlare, we probably want to use this.
# Some services with rate limiting  will block requests from
# cloudflare workers. (during testing I had experienced problems with NTFY)
# A working script that can be used with CloudFlare workers is included in 
# the root of Skybook's repository, at CFWorker-proxy-sample.js


instance_notification_proxy_url=""

[caching]

# If we are using CloudFlare & their caching, Skybook can cache data for anonymous users.
# Once the state of a guestbook changes (e.g, a new post becomes visible,
# a post is edited, the guestbook disables visibility of posts), 
# Skybook can purge the cache associated with that guestbook.
# Caching should never be enabled for authenticated users.
# We can disable caching if a request contains a 'session' cookie.
purging=false     
purge_endpoint="https://api.cloudflare.com/client/v4/zones/$ZONE_ID/purge_cache" # We can purge cache facing anonymous users using Cloudflare to speed up Skybook
[instances]
# Maximum number of characters that can exist within a
# guestbook's global filter (affecting all fields)
max_global_filter_length=5000
[captcha]
enabled = false
implementation = "cloudflare"                                       # cap | cloudflare
token_property_name = "cf-turnstile-response" # cap-token | cf-turnstile-response
site_key = "1x00000000000000000000AA" # cloudflare testing key | cap sitekey

challenge_url = "http://localhost:9000/"
verification_url = "https://challenges.cloudflare.com/turnstile/v0/siteverify" # https://challenges.cloudflare.com/turnstile/v0/siteverify | 127.0.0.1 (cap instance)

[invitations]
expiration_period_hours = 24

[users]
indefinite_locking_threshold = 3
expiration_threshold_days = 365
expiration_grace_period_days = 7

[posts]
perPage = 15

[fields]
name_max_length=50 # Maximum length of the name of a custom guestbook field
max_count=10
author_max_length = 50 # We treat the 'author' field as special, so it has specific limits
typical_max_length = 500
max_filter_length=2500

[rate_limits]
auth_window_ms = 60000             # 1 minute
auth_limit = 5
alteration_window_ms = 10000       # 10 seconds
alteration_limit_elevated = 8
alteration_limit_anonymous = 3
fetch_window_ms = 20000            # 20 seconds
fetch_limit = 25

[sessions]
expiry_days = 7

[tokens]
expiry_hours = 24

[jobs]
# How often to check for accounts which haven't
# been seen for at least users.expiration_threshold_days
# and schedule them for deletion 
expiration_sweep_interval_minutes = 60
lift_enforcements_interval_minutes = 60

[ip_blocking]

# If an IP address receives global_block_threshold number of infringements
# (e.g, blocked by N number of guestbook owners), 
# we can temporarily block them from creating SKybook posts entirely.
automated_enforcements_enabled = false
global_block_threshold = 15

blocking_timeframe_days_max = 30           # As IP addresses are not permanent identifiers, we expire all IP blocks after this timeframe.

# We can block specific anonymizers from accessing Skybook entirely.
# This overrides the blocking settings of individual guestbooks.
proxy_addresses_blocked = true         
vpn_addresses_blocked = true           
tor_addresses_blocked = true           
