services:
  skybook:
    image: skybook:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file: ./.env
    configs:
      - source: skybook_config
        target: /app/config.toml
  postgres:
    image: postgres
    restart: unless-stopped
    env_file: ./.env.postgres 
    environment:
      POSTGRES_DB: skybook
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql
      - ./schema:/docker-entrypoint-initdb.d/

configs:
  skybook_config:
    file: ./config.toml

networks:
  cap_default:
    driver: bridge
