CREATE TABLE reserved_usernames (
  username varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (username)
);-- ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO reserved_usernames VALUES
('0'),
('about'),
('access'),
('account'),
('accounts'),
('activate'),
('activities'),
('activity'),
('ad'),
('add'),
('address'),
('adm'),
('admin'),
('administration'),
('administrator'),
('ads'),
('adult'),
('advertising'),
('affiliate'),
('affiliates'),
('ajax'),
('all'),
('alpha'),
('analysis'),
('analytics'),
('android'),
('anon'),
('anonymous'),
('api'),
('app'),
('apps'),
('archive'),
('archives'),
('article'),
('asct'),
('asset'),
('atom'),
('auth'),
('authentication'),
('avatar'),
('backup'),
('balancer-manager'),
('banner'),
('banners'),
('beta'),
('billing'),
('bin'),
('blog'),
('blogs'),
('board'),
('book'),
('bookmark'),
('bot'),
('bots'),
('bug'),
('business'),
('cache'),
('cadastro'),
('calendar'),
('call'),
('campaign'),
('cancel'),
('captcha'),
('career'),
('careers'),
('cart'),
('categories'),
('category'),
('cgi'),
('cgi-bin'),
('changelog'),
('chat'),
('check'),
('checking'),
('checkout'),
('client'),
('cliente'),
('clients'),
('code'),
('codereview'),
('comercial'),
('comment'),
('comments'),
('communities'),
('community'),
('company'),
('compare'),
('compras'),
('config'),
('configuration'),
('connect'),
('contact'),
('contact-us'),
('contact_us'),
('contactus'),
('contest'),
('contribute'),
('corp'),
('create'),
('css'),
('dashboard'),
('data'),
('db'),
('default'),
('delete'),
('demo'),
('design'),
('designer'),
('destroy'),
('dev'),
('devel'),
('developer'),
('developers'),
('diagram'),
('diary'),
('dict'),
('dictionary'),
('die'),
('dir'),
('direct_messages'),
('directory'),
('dist'),
('doc'),
('docs'),
('documentation'),
('domain'),
('download'),
('downloads'),
('ecommerce'),
('edit'),
('editor'),
('edu'),
('education'),
('email'),
('employment'),
('empty'),
('end'),
('enterprise'),
('entries'),
('entry'),
('error'),
('errors'),
('eval'),
('event'),
('exit'),
('explore'),
('facebook'),
('faq'),
('favorite'),
('favorites'),
('feature'),
('features'),
('feed'),
('feedback'),
('feeds'),
('file'),
('files'),
('first'),
('flash'),
('fleet'),
('fleets'),
('flog'),
('follow'),
('followers'),
('following'),
('forgot'),
('form'),
('forum'),
('forums'),
('founder'),
('free'),
('friend'),
('friends'),
('ftp'),
('gadget'),
('gadgets'),
('game'),
('games'),
('get'),
('ghost'),
('gift'),
('gifts'),
('gist'),
('github'),
('graph'),
('group'),
('groups'),
('guest'),
('guests'),
('help'),
('home'),
('homepage'),
('host'),
('hosting'),
('hostmaster'),
('hostname'),
('howto'),
('hpg'),
('html'),
('http'),
('httpd'),
('https'),
('i'),
('iamges'),
('icon'),
('icons'),
('id'),
('idea'),
('ideas'),
('image'),
('images'),
('imap'),
('img'),
('index'),
('indice'),
('info'),
('information'),
('inquiry'),
('instagram'),
('intranet'),
('invitations'),
('invite'),
('ipad'),
('iphone'),
('irc'),
('is'),
('issue'),
('issues'),
('it'),
('item'),
('items'),
('java'),
('javascript'),
('job'),
('jobs'),
('join'),
('js'),
('json'),
('jump'),
('knowledgebase'),
('language'),
('languages'),
('last'),
('ldap-status'),
('legal'),
('license'),
('link'),
('links'),
('linux'),
('list'),
('lists'),
('log'),
('log-in'),
('log-out'),
('log_in'),
('log_out'),
('login'),
('logout'),
('logs'),
('m'),
('mac'),
('mail'),
('mail1'),
('mail2'),
('mail3'),
('mail4'),
('mail5'),
('mailer'),
('mailing'),
('maintenance'),
('manager'),
('manual'),
('map'),
('maps'),
('marketing'),
('master'),
('me'),
('media'),
('member'),
('members'),
('message'),
('messages'),
('messenger'),
('microblog'),
('microblogs'),
('mine'),
('mis'),
('mob'),
('mobile'),
('movie'),
('movies'),
('mp3'),
('msg'),
('msn'),
('music'),
('musicas'),
('mx'),
('my'),
('mysql'),
('name'),
('named'),
('nan'),
('navi'),
('navigation'),
('net'),
('network'),
('new'),
('news'),
('newsletter'),
('nick'),
('nickname'),
('notes'),
('noticias'),
('notification'),
('notifications'),
('notify'),
('ns'),
('ns1'),
('ns10'),
('ns2'),
('ns3'),
('ns4'),
('ns5'),
('ns6'),
('ns7'),
('ns8'),
('ns9'),
('null'),
('oauth'),
('oauth_clients'),
('offer'),
('offers'),
('official'),
('old'),
('online'),
('openid'),
('operator'),
('order'),
('orders'),
('organization'),
('organizations'),
('overview'),
('owner'),
('owners'),
('page'),
('pager'),
('pages'),
('panel'),
('password'),
('payment'),
('perl'),
('phone'),
('photo'),
('photoalbum'),
('photos'),
('php'),
('phpmyadmin'),
('phppgadmin'),
('phpredisadmin'),
('pic'),
('pics'),
('ping'),
('plan'),
('plans'),
('plugin'),
('plugins'),
('policy'),
('pop'),
('pop3'),
('popular'),
('portal'),
('post'),
('postfix'),
('postmaster'),
('posts'),
('pr'),
('premium'),
('press'),
('price'),
('pricing'),
('privacy'),
('privacy-policy'),
('privacy_policy'),
('privacypolicy'),
('private'),
('product'),
('products'),
('profile'),
('project'),
('projects'),
('promo'),
('pub'),
('public'),
('purpose'),
('put'),
('python'),
('query'),
('random'),
('ranking'),
('read'),
('readme'),
('recent'),
('recruit'),
('recruitment'),
('register'),
('registration'),
('release'),
('remove'),
('replies'),
('report'),
('reports'),
('repositories'),
('repository'),
('req'),
('request'),
('requests'),
('reset'),
('roc'),
('root'),
('rss'),
('ruby'),
('rule'),
('sag'),
('sale'),
('sales'),
('sample'),
('samples'),
('save'),
('school'),
('script'),
('scripts'),
('search'),
('secure'),
('security'),
('self'),
('send'),
('server'),
('server-info'),
('server-status'),
('service'),
('services'),
('session'),
('sessions'),
('setting'),
('settings'),
('setup'),
('share'),
('shop'),
('show'),
('sign-in'),
('sign-up'),
('sign_in'),
('sign_up'),
('signin'),
('signout'),
('signup'),
('site'),
('sitemap'),
('sites'),
('smartphone'),
('smtp'),
('soporte'),
('source'),
('spec'),
('special'),
('sql'),
('src'),
('ssh'),
('ssl'),
('ssladmin'),
('ssladministrator'),
('sslwebmaster'),
('staff'),
('stage'),
('staging'),
('start'),
('stat'),
('state'),
('static'),
('stats'),
('status'),
('store'),
('stores'),
('stories'),
('style'),
('styleguide'),
('stylesheet'),
('stylesheets'),
('subdomain'),
('subscribe'),
('subscriptions'),
('suporte'),
('support'),
('svn'),
('swf'),
('sys'),
('sysadmin'),
('sysadministrator'),
('system'),
('tablet'),
('tablets'),
('tag'),
('talk'),
('task'),
('tasks'),
('team'),
('teams'),
('tech'),
('telnet'),
('term'),
('terms'),
('terms-of-service'),
('terms_of_service'),
('termsofservice'),
('test'),
('test1'),
('test2'),
('test3'),
('teste'),
('testing'),
('tests'),
('theme'),
('themes'),
('thread'),
('threads'),
('tmp'),
('todo'),
('tool'),
('tools'),
('top'),
('topic'),
('topics'),
('tos'),
('tour'),
('translations'),
('trends'),
('tutorial'),
('tux'),
('tv'),
('twitter'),
('undef'),
('unfollow'),
('unsubscribe'),
('update'),
('upload'),
('uploads'),
('url'),
('usage'),
('user'),
('username'),
('users'),
('usuario'),
('vendas'),
('ver'),
('version'),
('video'),
('videos'),
('visitor'),
('watch'),
('weather'),
('web'),
('webhook'),
('webhooks'),
('webmail'),
('webmaster'),
('website'),
('websites'),
('welcome'),
('widget'),
('widgets'),
('wiki'),
('win'),
('windows'),
('word'),
('work'),
('works'),
('workshop'),
('ww'),
('wws'),
('www'),
('www1'),
('www2'),
('www3'),
('www4'),
('www5'),
('www6'),
('www7'),
('wwws'),
('wwww'),
('xfn'),
('xml'),
('xmpp'),
('xpg'),
('xxx'),
('yaml'),
('year'),
('yml'),
('you'),
('yourdomain'),
('yourname'),
('yoursite'),
('yourusername'),
('kaiju');
CREATE TABLE users (
  name TEXT PRIMARY KEY, --CHECK (
    --NOT EXISTS (
   --   SELECT 1 FROM reserved_usernames r
    --  WHERE r.value = users.name
   -- )
 -- )
 
  identifier UUID NOT NULL DEFAULT gen_random_uuid(),
  ip_hash TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  totp_secret TEXT,
  mfa_recovery TEXT[],
  can_login BOOLEAN NOT NULL DEFAULT TRUE,
  can_post BOOLEAN NOT NULL DEFAULT TRUE,
  can_delete_account BOOLEAN NOT NULL DEFAULT TRUE,
  can_change_password BOOLEAN NOT NULL DEFAULT TRUE,
  can_change_username BOOLEAN NOT NULL DEFAULT FALSE,
  can_create_invitations BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen TIMESTAMPTZ NOT NULL DEFAULT now(),
  is_superadmin BOOLEAN NOT NULL DEFAULT FALSE,
  can_be_blocked BOOLEAN NOT NULL DEFAULT TRUE, -- Should only be needed if superadmin
  UNIQUE(identifier)
);

CREATE TABLE instances (
  name TEXT PRIMARY KEY REFERENCES users(name) ON DELETE CASCADE,
  is_visible BOOLEAN NOT NULL DEFAULT TRUE, -- -- -- --  -- --
  submission_enabled BOOLEAN NOT NULL DEFAULT TRUE, -- -- --
  --replying_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  approval_required BOOLEAN NOT NULL DEFAULT FALSE,
  flagging_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  queue_on_filtered BOOLEAN NOT NULL DEFAULT TRUE,
  enforced_lock BOOLEAN NOT NULL DEFAULT FALSE,
  custom_filter TEXT,
  blocklist_proxy_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  blocklist_vpn_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  blocklist_tor_enabled BOOLEAN NOT NULL DEFAULT FALSE
);


CREATE TABLE fields (
  instance TEXT NOT NULL REFERENCES instances(name) ON DELETE CASCADE,
  name TEXT NOT NULL,
  is_public BOOLEAN NOT NULL DEFAULT TRUE,
  is_special BOOLEAN NOT NULL DEFAULT FALSE,
  is_required BOOLEAN NOT NULL DEFAULT FALSE,
  replacement TEXT,
  filter TEXT,
  PRIMARY KEY (instance, name)
);
CREATE TABLE posts (
  seq BIGSERIAL PRIMARY KEY,
  instance TEXT NOT NULL REFERENCES instances(name) ON DELETE CASCADE,
  ip_hash TEXT NOT NULL,
  identifier TEXT UNIQUE NOT NULL,
  authenticated_user_identifier UUID REFERENCES users(identifier) ON DELETE SET NULL,
  --parent TEXT REFERENCES posts(identifier) ON DELETE CASCADE,
  reply TEXT,
  author TEXT NOT NULL DEFAULT 'anonymous',
  content TEXT NOT NULL,
  extra JSONB NOT NULL DEFAULT '{}',
  is_visible BOOLEAN NOT NULL DEFAULT TRUE,
  is_queued BOOLEAN NOT NULL DEFAULT FALSE,
  flag_count INTEGER NOT NULL DEFAULT 0,
  can_flag BOOLEAN NOT NULL DEFAULT TRUE,
  is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
  is_highlighted BOOLEAN NOT NULL DEFAULT FALSE,
  added TIMESTAMPTZ NOT NULL DEFAULT now(),
  --can_reply BOOLEAN NOT NULL DEFAULT TRUE,
  can_block BOOLEAN NOT NULL DEFAULT TRUE,
  sys_lock BOOLEAN NOT NULL DEFAULT FALSE, 
  UNIQUE (instance, identifier)
);

CREATE TABLE post_flags (
  instance TEXT NOT NULL REFERENCES instances(name) ON DELETE CASCADE,
  identifier TEXT NOT NULL REFERENCES posts(identifier) ON DELETE CASCADE,
  user_identifier UUID REFERENCES users(identifier) ON DELETE SET NULL,
  ip_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX post_flags_unique_ip ON post_flags (instance, identifier, ip_hash);
CREATE UNIQUE INDEX post_flags_unique_user ON post_flags (instance, identifier, user_identifier) WHERE user_identifier IS NOT null;
CREATE TABLE tokens (
  instance TEXT NOT NULL,
  identifier TEXT NOT NULL,
  token TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (instance, identifier)
);
CREATE INDEX CONCURRENTLY tokens_expires_at_idx ON tokens (expires_at);
CREATE TABLE invitations (
  token TEXT PRIMARY KEY NOT NULL,
  created_by UUID NOT NULL REFERENCES users(identifier) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_used TIMESTAMPTZ,
  uses INTEGER NOT NULL DEFAULT 0,
  UNIQUE (token)
);
CREATE TABLE overrides (
  instance TEXT REFERENCES instances(name),
  name TEXT NOT NULL CHECK (name IN (
  'is_visible', 'submission_enabled', 'replying_enabled', 'approval_required', 'flagging_enabled', 'queue_on_filtered'
  )),
  value BOOLEAN NOT NULL,
  UNIQUE (instance, name)
);
CREATE UNIQUE INDEX overrides_global_uidx ON overrides (name) WHERE instance IS NULL;
CREATE UNIQUE INDEX overrides_instance_uidx ON overrides (instance, name) WHERE instance IS NOT NULL;

CREATE TABLE service_settings (
  name TEXT PRIMARY KEY,
  value BOOLEAN NOT NULL,
  message TEXT
);
INSERT INTO service_settings (name, value) VALUES ('signup_enabled', false), ('totp_enabled', true),('login_enabled',true),('account_deletion_enabled',true);
-- IP address blocking
CREATE TABLE instance_blocks (
  instance TEXT NOT NULL REFERENCES instances(name) ON DELETE CASCADE,
  ip_hash TEXT NOT NULL,
  user_identifier UUID REFERENCES users(identifier) ON DELETE CASCADE,
  blocked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  reason TEXT,
  PRIMARY KEY (instance, ip_hash)
);
CREATE UNIQUE INDEX instance_blocks_unique_user ON instance_blocks (instance, user_identifier) WHERE user_identifier IS NOT NULL;
CREATE UNIQUE INDEX instance_blocks_unique_ip ON instance_blocks (instance, ip_hash) WHERE ip_hash IS NOT NULL;
-- CREATE TABLE instance_user_blocks (
--   instance TEXT NOT NULL REFERENCES instances(name) ON DELETE CASCADE,
--   user_identifier UUID REFERENCES users(identifier),
--   blocked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
--   reason TEXT,
--   PRIMARY KEY (instance, user_identifier)
-- );
-- CREATE INDEX instance_user_blocks_user_idx ON instance_user_blocks (user_identifier);

CREATE TABLE ip_block_stats (
  ip_hash TEXT PRIMARY KEY,
  block_count INTEGER NOT NULL DEFAULT 1,
  first_blocked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_blocked_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE global_ip_blocks (
  ip_hash TEXT PRIMARY KEY,
  blocked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  reason TEXT
);

CREATE TABLE user_enforcements (
    identifier UUID PRIMARY KEY REFERENCES users(identifier) ON DELETE CASCADE,
    status TEXT NOT NULL CHECK (status IN ('active','posting_blocked','locked')),
    locked_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    enforcements JSONB NOT NULL DEFAULT '{}',
    block_count INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE blocklist_ranges (
  source TEXT NOT NULL,
  range CIDR NOT NULL,
  added TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_blocklist_range ON blocklist_ranges USING gist (range inet_ops);
CREATE TABLE filters (
    identifier TEXT PRIMARY KEY, -- This should be the filter name
    filter TEXT NOT NULL
);
CREATE TABLE instance_filters (
    instance TEXT NOT NULL REFERENCES instances(name) ON DELETE CASCADE,
    filter TEXT NOT NULL REFERENCES filters(identifier) ON DELETE CASCADE,
    enabled_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (instance, filter)
);
CREATE TABLE sessions (
  token TEXT PRIMARY KEY,
  user_name TEXT NOT NULL REFERENCES users(name),
  user_identifier UUID NOT NULL REFERENCES users(identifier) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL DEFAULT (now() + INTERVAL '1 week')
);
CREATE INDEX CONCURRENTLY sessions_expires_at_idx ON sessions (expires_at);